name: Auto increment patch version

on:
  push:
    branches:
      - release
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup git config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Create a version
        run : |
          pnpm run changeset:auto-path-increment
          pnpm run changeset:version
          pnpm run changeset:tag
          git add . && git commit -m "chore: auto increment patch version"
          git push --tags
