name: Create a pull request release to main

on:
  pull_request:
    types: [closed]
    branches:
      - release

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a pull pull-request
        run : |
          DIFF=`git --no-pager log --pretty=format:"- %s %d %aE %ai" origin/main..origin/release --no-merges | sed -r 's/[0-9]*\+(.*)@users.noreply.github.com/@\1/g'`

          gh pr create --base main --head release --title "$TITLE" --body "$DIFF"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: "chore: release to main"
